/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as MarketRouteImport } from './routes/market'
import { Route as DemandRouteImport } from './routes/demand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated/my.listings'
import { Route as AuthenticatedMyDemandRouteImport } from './routes/_authenticated/my.demand'

const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandRoute = DemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my/listings',
  path: '/my/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyDemandRoute = AuthenticatedMyDemandRouteImport.update({
  id: '/my/demand',
  path: '/my/demand',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demand': typeof DemandRoute
  '/market': typeof MarketRoute
  '/prices': typeof PricesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my/demand': typeof AuthenticatedMyDemandRoute
  '/my/listings': typeof AuthenticatedMyListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demand': typeof DemandRoute
  '/market': typeof MarketRoute
  '/prices': typeof PricesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my/demand': typeof AuthenticatedMyDemandRoute
  '/my/listings': typeof AuthenticatedMyListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demand': typeof DemandRoute
  '/market': typeof MarketRoute
  '/prices': typeof PricesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/my/demand': typeof AuthenticatedMyDemandRoute
  '/_authenticated/my/listings': typeof AuthenticatedMyListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demand'
    | '/market'
    | '/prices'
    | '/admin'
    | '/my/demand'
    | '/my/listings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demand'
    | '/market'
    | '/prices'
    | '/admin'
    | '/my/demand'
    | '/my/listings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demand'
    | '/market'
    | '/prices'
    | '/_authenticated/admin'
    | '/_authenticated/my/demand'
    | '/_authenticated/my/listings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemandRoute: typeof DemandRoute
  MarketRoute: typeof MarketRoute
  PricesRoute: typeof PricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand': {
      id: '/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof DemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my/listings': {
      id: '/_authenticated/my/listings'
      path: '/my/listings'
      fullPath: '/my/listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my/demand': {
      id: '/_authenticated/my/demand'
      path: '/my/demand'
      fullPath: '/my/demand'
      preLoaderRoute: typeof AuthenticatedMyDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMyDemandRoute: typeof AuthenticatedMyDemandRoute
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMyDemandRoute: AuthenticatedMyDemandRoute,
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemandRoute: DemandRoute,
  MarketRoute: MarketRoute,
  PricesRoute: PricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
